# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'food_delivery' do
  pod 'AppCenter/Push', '~> 1.13.2'
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for food_delivery

  

  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  target 'food_deliveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'food_delivery-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for food_delivery-tvOS

  target 'food_delivery-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
